# Generated by Django 4.2.10 on 2025-03-20 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_category_slug_remove_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/", verbose_name="logo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="diameter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Rim diameter in inches",
                null=True,
                verbose_name="diameter",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="profile",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Tire profile height as percentage of width",
                null=True,
                verbose_name="profile",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Tire width in millimeters",
                max_digits=4,
                null=True,
                verbose_name="width",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.brand",
                verbose_name="brand",
            ),
        ),
    ]
