# Generated by Django 4.2.10 on 2025-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_images_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
