# Generated by Django 4.2.10 on 2025-05-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="products.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("name", "category")},
        ),
    ]
