# Generated by Django 4.2.10 on 2025-05-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_make_brand_category_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bolt_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of bolt holes",
                null=True,
                verbose_name="bolt count",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="center_bore",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Center bore diameter in millimeters",
                max_digits=5,
                null=True,
                verbose_name="center bore",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="et_offset",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Wheel offset in millimeters",
                null=True,
                verbose_name="ET offset",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pcd",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Pitch Circle Diameter in millimeters",
                max_digits=5,
                null=True,
                verbose_name="PCD",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wheel_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Wheel width in inches",
                max_digits=4,
                null=True,
                verbose_name="wheel width",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="diameter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Rim/Wheel diameter in inches",
                null=True,
                verbose_name="diameter",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="profile",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Tire profile height as percentage of width",
                null=True,
                verbose_name="tire profile",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Tire width in millimeters",
                max_digits=4,
                null=True,
                verbose_name="tire width",
            ),
        ),
    ]
